projects:
  article:
    schemaPath: src/graphql/schema.json
    includes:
      - src/plugins/api/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/plugins/api/index.ts
        docsFilePath: src/plugins/api
        maxDepth: 2
extensions:
  amplify:
    version: 3
