projects:
  aoyacafeberry:
    schemaPath: src/graphql/schema.json
    includes:
      - src/plugins/api/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/api/types.ts
        docsFilePath: src/plugins/api
extensions:
  amplify:
    version: 3
