export const ROUTE = { HOME: "/", BENTO: "/bento", LINK: "/link" };
export const IMAGE_DIR = "/img/";
export const LUNCH_IMAGE_PATH = IMAGE_DIR + "lunches/";
export const ACCESSORIES_IMAGE_PATH = IMAGE_DIR + "accessories/";
export const TOP_IMAGE_PATH = IMAGE_DIR + "top/";
export const VEGETABLES_IMAGE_PATH = IMAGE_DIR + "vegetables/";
export const BENTO_IMAGE_PATH = IMAGE_DIR + "bentos/";
export const LINK_IMAGE_PATH = IMAGE_DIR + "links/";
export const LOADING_ANIMATION_DOM = "loading-animation";
